<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/inc/bootstrap.php'; $user=ru_admin_require(); $id=(int)($_GET['id']??0); $action=(string)($_GET['action']??'list');
if($_SERVER['REQUEST_METHOD']==='POST'){ if(!ru_csrf_check())ru_abort(400); if($action==='delete'&&$id){ru_exec('DELETE FROM '.ru_t('menu').' WHERE id=?',[$id]);ru_flash('success','Menü silindi.');ru_redirect('/admin/menus.php');}
$params=[ru_admin_input('location','header'),ru_admin_input('label'),ru_admin_input('url','#'),ru_admin_input('target','_self'),(int)($_POST['sort_order']??0),isset($_POST['is_active'])?1:0];
if($id){$params[]=$id;ru_exec('UPDATE '.ru_t('menu').' SET location=?,label=?,url=?,target=?,sort_order=?,is_active=?,updated_at=NOW() WHERE id=?',$params);}else{ru_exec('INSERT INTO '.ru_t('menu').' (location,label,url,target,sort_order,is_active) VALUES (?,?,?,?,?,?)',$params);}ru_flash('success','Menü kaydedildi.');ru_redirect('/admin/menus.php');}
ob_start(); if($action==='new'||($action==='edit'&&$id)): $row=$id?ru_fetch('SELECT * FROM '.ru_t('menu').' WHERE id=?',[$id]):[]; ?>
<section class="admin-panel"><div class="admin-panel__head"><h2><?= $id?'Menü Düzenle':'Menü Ekle' ?></h2><a class="btn" href="/admin/menus.php">Listeye Dön</a></div><form class="admin-form" method="post"><?= ru_csrf_field() ?><div class="admin-row admin-row--3"><label>Konum<select name="location"><?php foreach(['header','footer_1','footer_2','footer_3','mobile'] as $loc): ?><option value="<?= h($loc) ?>" <?= ($row['location']??'header')===$loc?'selected':'' ?>><?= h($loc) ?></option><?php endforeach; ?></select></label><label>Etiket<input name="label" value="<?= h($row['label']??'') ?>" required></label><label>URL<input name="url" value="<?= h($row['url']??'') ?>" required></label></div><div class="admin-row"><label>Hedef<select name="target"><option value="_self">Aynı sekme</option><option value="_blank" <?= ($row['target']??'')==='_blank'?'selected':'' ?>>Yeni sekme</option></select></label><label>Sıra<input type="number" name="sort_order" value="<?= h($row['sort_order']??0) ?>"></label></div><label><input type="checkbox" name="is_active" value="1" <?= (int)($row['is_active']??1)?'checked':'' ?>> Aktif</label><button class="btn btn--primary">Kaydet</button></form></section>
<?php else: $rows=ru_fetch_all('SELECT * FROM '.ru_t('menu').' ORDER BY location ASC, sort_order ASC'); ?>
<section class="admin-panel"><div class="admin-panel__head"><h2>Menü</h2><a class="btn btn--primary" href="/admin/menus.php?action=new">Yeni Menü</a></div><table class="admin-table"><thead><tr><th>Konum</th><th>Etiket</th><th>URL</th><th>Durum</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?= h($row['location']) ?></td><td><?= h($row['label']) ?></td><td><?= h($row['url']) ?></td><td><span class="badge <?= (int)$row['is_active']?'':'badge--off' ?>"><?= (int)$row['is_active']?'Aktif':'Pasif' ?></span></td><td class="admin-actions"><a class="btn" href="/admin/menus.php?action=edit&id=<?= h($row['id']) ?>">Düzenle</a><form method="post" action="/admin/menus.php?action=delete&id=<?= h($row['id']) ?>" onsubmit="return confirm('Silinsin mi?')"><?= ru_csrf_field() ?><button class="btn btn--danger">Sil</button></form></td></tr><?php endforeach; ?></tbody></table></section>
<?php endif; ru_admin_layout('Menü',ob_get_clean(),$user);
