<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/inc/bootstrap.php';
$user = ru_admin_require();
$id = (int)($_GET['id'] ?? 0); $action = (string)($_GET['action'] ?? 'list');
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!ru_csrf_check()) ru_abort(400);
    if ($action === 'delete' && $id) { ru_exec('DELETE FROM '.ru_t('pages').' WHERE id=?',[$id]); ru_flash('success','Sayfa silindi.'); ru_redirect('/admin/pages.php'); }
    $title=ru_admin_input('title'); $slug=ru_admin_input('slug') ?: ru_slugify($title);
    $params=[$slug,$title,ru_admin_input('subtitle'),ru_admin_input('excerpt'),(string)($_POST['content']??''),ru_admin_input('meta_description'),ru_admin_input('template','default'),(int)($_POST['sort_order']??0),isset($_POST['is_active'])?1:0,isset($_POST['show_in_header'])?1:0,isset($_POST['show_in_footer'])?1:0];
    if($id){$params[]=$id;ru_exec('UPDATE '.ru_t('pages').' SET slug=?,title=?,subtitle=?,excerpt=?,content=?,meta_description=?,template=?,sort_order=?,is_active=?,show_in_header=?,show_in_footer=?,updated_at=NOW() WHERE id=?',$params);} else {ru_exec('INSERT INTO '.ru_t('pages').' (slug,title,subtitle,excerpt,content,meta_description,template,sort_order,is_active,show_in_header,show_in_footer) VALUES (?,?,?,?,?,?,?,?,?,?,?)',$params);}
    ru_flash('success','Sayfa kaydedildi.'); ru_redirect('/admin/pages.php');
}
ob_start();
if($action==='new'||($action==='edit'&&$id)): $row=$id?ru_fetch('SELECT * FROM '.ru_t('pages').' WHERE id=?',[$id]):[]; ?>
<section class="admin-panel"><div class="admin-panel__head"><h2><?= $id?'Sayfa Düzenle':'Sayfa Ekle' ?></h2><a class="btn" href="/admin/pages.php">Listeye Dön</a></div><form class="admin-form" method="post"><?= ru_csrf_field() ?><div class="admin-row"><label>Başlık<input name="title" value="<?= h($row['title']??'') ?>" required></label><label>Slug<input name="slug" value="<?= h($row['slug']??'') ?>"></label></div><label>Alt başlık<input name="subtitle" value="<?= h($row['subtitle']??'') ?>"></label><label>Özet<textarea name="excerpt"><?= h($row['excerpt']??'') ?></textarea></label><label>İçerik HTML<textarea name="content" style="min-height:300px"><?= h($row['content']??'') ?></textarea></label><label>Meta açıklama<textarea name="meta_description"><?= h($row['meta_description']??'') ?></textarea></label><div class="admin-row admin-row--3"><label>Şablon<select name="template"><option value="default">default</option><option value="contact" <?= ($row['template']??'')==='contact'?'selected':'' ?>>contact</option></select></label><label>Sıra<input type="number" name="sort_order" value="<?= h($row['sort_order']??0) ?>"></label><label><input type="checkbox" name="is_active" value="1" <?= (int)($row['is_active']??1)?'checked':'' ?>> Aktif</label></div><div class="admin-actions"><label><input type="checkbox" name="show_in_header" value="1" <?= (int)($row['show_in_header']??0)?'checked':'' ?>> Header</label><label><input type="checkbox" name="show_in_footer" value="1" <?= (int)($row['show_in_footer']??0)?'checked':'' ?>> Footer</label></div><button class="btn btn--primary">Kaydet</button></form></section>
<?php else: $rows=ru_fetch_all('SELECT * FROM '.ru_t('pages').' ORDER BY sort_order ASC,id DESC'); ?>
<section class="admin-panel"><div class="admin-panel__head"><h2>Sayfalar</h2><a class="btn btn--primary" href="/admin/pages.php?action=new">Yeni Sayfa</a></div><table class="admin-table"><thead><tr><th>Başlık</th><th>Slug</th><th>Şablon</th><th>Durum</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?= h($row['title']) ?></td><td><?= h($row['slug']) ?></td><td><?= h($row['template']) ?></td><td><span class="badge <?= (int)$row['is_active']?'':'badge--off' ?>"><?= (int)$row['is_active']?'Aktif':'Pasif' ?></span></td><td class="admin-actions"><a class="btn" href="/admin/pages.php?action=edit&id=<?= h($row['id']) ?>">Düzenle</a><form method="post" action="/admin/pages.php?action=delete&id=<?= h($row['id']) ?>" onsubmit="return confirm('Silinsin mi?')"><?= ru_csrf_field() ?><button class="btn btn--danger">Sil</button></form></td></tr><?php endforeach; ?></tbody></table></section>
<?php endif; ru_admin_layout('Sayfalar', ob_get_clean(), $user);
