<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/inc/bootstrap.php'; $user=ru_admin_require(); $id=(int)($_GET['id']??0); $action=(string)($_GET['action']??'list');
if($_SERVER['REQUEST_METHOD']==='POST'){ if(!ru_csrf_check())ru_abort(400); if($action==='delete'&&$id){ru_exec('DELETE FROM '.ru_t('slider').' WHERE id=?',[$id]);ru_flash('success','Slider silindi.');ru_redirect('/admin/sliders.php');}
try{$image=ru_admin_upload('image_file','slider')?:ru_admin_input('image');$imageMobile=ru_admin_upload('image_mobile_file','slider')?:ru_admin_input('image_mobile');}catch(Throwable $e){ru_flash('error',$e->getMessage());ru_redirect($id?'/admin/sliders.php?action=edit&id='.$id:'/admin/sliders.php?action=new');}
$params=[ru_admin_input('title'),ru_admin_input('subtitle'),ru_admin_input('description'),$image,$imageMobile,ru_admin_input('link_url'),ru_admin_input('link_text'),ru_admin_input('link_target','_self'),ru_admin_input('text_position','left'),ru_admin_input('text_color','light'),(int)($_POST['overlay_opacity']??40),(int)($_POST['sort_order']??0),isset($_POST['is_active'])?1:0];
if($id){$params[]=$id;ru_exec('UPDATE '.ru_t('slider').' SET title=?,subtitle=?,description=?,image=?,image_mobile=?,link_url=?,link_text=?,link_target=?,text_position=?,text_color=?,overlay_opacity=?,sort_order=?,is_active=?,updated_at=NOW() WHERE id=?',$params);}else{ru_exec('INSERT INTO '.ru_t('slider').' (title,subtitle,description,image,image_mobile,link_url,link_text,link_target,text_position,text_color,overlay_opacity,sort_order,is_active) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',$params);} ru_flash('success','Slider kaydedildi.');ru_redirect('/admin/sliders.php');}
ob_start(); if($action==='new'||($action==='edit'&&$id)): $row=$id?ru_fetch('SELECT * FROM '.ru_t('slider').' WHERE id=?',[$id]):[]; ?>
<section class="admin-panel"><div class="admin-panel__head"><h2><?= $id?'Slider Düzenle':'Slider Ekle' ?></h2><a class="btn" href="/admin/sliders.php">Listeye Dön</a></div><form class="admin-form" method="post" enctype="multipart/form-data"><?= ru_csrf_field() ?><div class="admin-row"><label>Başlık<input name="title" value="<?= h($row['title']??'') ?>" required></label><label>Alt başlık<input name="subtitle" value="<?= h($row['subtitle']??'') ?>"></label></div><label>Açıklama<textarea name="description"><?= h($row['description']??'') ?></textarea></label><div class="admin-row"><label>Görsel yolu<input name="image" value="<?= h($row['image']??'') ?>"></label><label>Görsel yükle<input type="file" name="image_file" accept="image/*"></label></div><div class="admin-row"><label>Mobil görsel yolu<input name="image_mobile" value="<?= h($row['image_mobile']??'') ?>"></label><label>Mobil görsel yükle<input type="file" name="image_mobile_file" accept="image/*"></label></div><div class="admin-row"><label>Link<input name="link_url" value="<?= h($row['link_url']??'') ?>"></label><label>Buton metni<input name="link_text" value="<?= h($row['link_text']??'') ?>"></label></div><div class="admin-row admin-row--3"><label>Pozisyon<select name="text_position"><option>left</option><option <?= ($row['text_position']??'')==='center'?'selected':'' ?>>center</option><option <?= ($row['text_position']??'')==='right'?'selected':'' ?>>right</option></select></label><label>Overlay %<input type="number" name="overlay_opacity" value="<?= h($row['overlay_opacity']??40) ?>"></label><label>Sıra<input type="number" name="sort_order" value="<?= h($row['sort_order']??0) ?>"></label></div><input type="hidden" name="link_target" value="_self"><input type="hidden" name="text_color" value="light"><label><input type="checkbox" name="is_active" value="1" <?= (int)($row['is_active']??1)?'checked':'' ?>> Aktif</label><button class="btn btn--primary">Kaydet</button></form></section>
<?php else: $rows=ru_fetch_all('SELECT * FROM '.ru_t('slider').' ORDER BY sort_order ASC,id DESC'); ?>
<section class="admin-panel"><div class="admin-panel__head"><h2>Slider</h2><a class="btn btn--primary" href="/admin/sliders.php?action=new">Yeni Slider</a></div><table class="admin-table"><thead><tr><th>Başlık</th><th>Link</th><th>Durum</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?= h($row['title']) ?></td><td><?= h($row['link_url']) ?></td><td><span class="badge <?= (int)$row['is_active']?'':'badge--off' ?>"><?= (int)$row['is_active']?'Aktif':'Pasif' ?></span></td><td class="admin-actions"><a class="btn" href="/admin/sliders.php?action=edit&id=<?= h($row['id']) ?>">Düzenle</a><form method="post" action="/admin/sliders.php?action=delete&id=<?= h($row['id']) ?>" onsubmit="return confirm('Silinsin mi?')"><?= ru_csrf_field() ?><button class="btn btn--danger">Sil</button></form></td></tr><?php endforeach; ?></tbody></table></section>
<?php endif; ru_admin_layout('Slider',ob_get_clean(),$user);
