<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/inc/bootstrap.php'; $user=ru_admin_require(); if(!ru_admin_can('admin',$user)) ru_abort(403);
$id=(int)($_GET['id']??0); $action=(string)($_GET['action']??'list');
if($_SERVER['REQUEST_METHOD']==='POST'){ if(!ru_csrf_check())ru_abort(400); if($action==='delete'&&$id){ru_exec('DELETE FROM '.ru_t('users').' WHERE id=? AND id<>?',[$id,(int)$user['id']]);ru_flash('success','Kullanıcı silindi.');ru_redirect('/admin/users.php');}
$params=[ru_admin_input('email'),ru_admin_input('full_name'),ru_admin_input('phone'),ru_admin_input('role','admin'),isset($_POST['is_active'])?1:0]; $pass=(string)($_POST['password']??'');
if($id){ if($pass!==''){ $params[]=password_hash($pass,PASSWORD_BCRYPT,['cost'=>12]); $params[]=$id; ru_exec('UPDATE '.ru_t('users').' SET email=?,full_name=?,phone=?,role=?,is_active=?,password_hash=?,updated_at=NOW() WHERE id=?',$params);} else {$params[]=$id; ru_exec('UPDATE '.ru_t('users').' SET email=?,full_name=?,phone=?,role=?,is_active=?,updated_at=NOW() WHERE id=?',$params);} } else { $params[]=password_hash($pass ?: bin2hex(random_bytes(8)),PASSWORD_BCRYPT,['cost'=>12]); ru_exec('INSERT INTO '.ru_t('users').' (email,full_name,phone,role,is_active,password_hash) VALUES (?,?,?,?,?,?)',$params); }
ru_flash('success','Kullanıcı kaydedildi.');ru_redirect('/admin/users.php');}
ob_start(); if($action==='new'||($action==='edit'&&$id)): $row=$id?ru_fetch('SELECT * FROM '.ru_t('users').' WHERE id=?',[$id]):[]; ?>
<section class="admin-panel"><div class="admin-panel__head"><h2><?= $id?'Kullanıcı Düzenle':'Kullanıcı Ekle' ?></h2><a class="btn" href="/admin/users.php">Listeye Dön</a></div><form class="admin-form" method="post"><?= ru_csrf_field() ?><div class="admin-row"><label>E-posta<input type="email" name="email" value="<?= h($row['email']??'') ?>" required></label><label>Ad Soyad<input name="full_name" value="<?= h($row['full_name']??'') ?>"></label></div><div class="admin-row admin-row--3"><label>Telefon<input name="phone" value="<?= h($row['phone']??'') ?>"></label><label>Rol<select name="role"><?php foreach(['superadmin','admin','editor','viewer'] as $role): ?><option value="<?= h($role) ?>" <?= ($row['role']??'admin')===$role?'selected':'' ?>><?= h($role) ?></option><?php endforeach; ?></select></label><label>Şifre<input type="password" name="password" placeholder="<?= $id?'boş bırakılırsa değişmez':'zorunlu' ?>"></label></div><label><input type="checkbox" name="is_active" value="1" <?= (int)($row['is_active']??1)?'checked':'' ?>> Aktif</label><button class="btn btn--primary">Kaydet</button></form></section>
<?php else: $rows=ru_fetch_all('SELECT * FROM '.ru_t('users').' ORDER BY id DESC'); ?>
<section class="admin-panel"><div class="admin-panel__head"><h2>Kullanıcılar</h2><a class="btn btn--primary" href="/admin/users.php?action=new">Yeni Kullanıcı</a></div><table class="admin-table"><thead><tr><th>Ad</th><th>E-posta</th><th>Rol</th><th>Son giriş</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?= h($row['full_name']) ?></td><td><?= h($row['email']) ?></td><td><span class="badge"><?= h($row['role']) ?></span></td><td><?= h(ru_date($row['last_login_at'],'d.m.Y H:i')) ?></td><td class="admin-actions"><a class="btn" href="/admin/users.php?action=edit&id=<?= h($row['id']) ?>">Düzenle</a><form method="post" action="/admin/users.php?action=delete&id=<?= h($row['id']) ?>" onsubmit="return confirm('Silinsin mi?')"><?= ru_csrf_field() ?><button class="btn btn--danger">Sil</button></form></td></tr><?php endforeach; ?></tbody></table></section>
<?php endif; ru_admin_layout('Kullanıcılar',ob_get_clean(),$user);
